generate:
  - types
  - client

filter:
  tags:
    - ItemsService
  operations:
    # SystemService
    - getSystemInfoPublic
    # LibraryService
    - getLibraryMediafolders
    # UserService
    - postUsersAuthenticatebyname
    # UserLibraryService
    - getUsersByUseridItemsById
    - postUsersByUseridFavoriteitemsById
    - deleteUsersByUseridFavoriteitemsById
    # ArtistsService
    - getArtists
    - getArtistsByName
    # MusicGenresService
    - getMusicgenres
